name: Deploy to Itch.io

on:
  push:
    branches:
      - main # Or 'master' depending on your default branch name

jobs:
  export_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Export Godot Web Build
        id: export
        uses: firebelley/godot-export@v5
        with:
          godot_executable_download_url: https://github.com/godotengine/godot/releases/download/4.2.2-stable/Godot_v4.2.2-stable_linux.x86_64.zip
          godot_export_templates_download_url: https://github.com/godotengine/godot/releases/download/4.2.2-stable/Godot_v4.2.2-stable_export_templates.tpz
          relative_project_path: ./
          archive_output: true

      - name: Publish to Itch.io
        uses: manleydev/butler-publish-itchio-action@master
        env:
          BUTLER_CREDENTIALS: ${{ secrets.BUTLER_CREDENTIALS }}
          CHANNEL: html
          ITCH_GAME: ${{ secrets.ITCH_GAME }}
          PACKAGE: ${{ steps.export.outputs.archive_directory }}/Web.zip
