name: Deploy to Itch.io

on:
  push:
    branches:
      - main

jobs:
  export_and_deploy:
    runs-on: ubuntu-latest
    name: Export and Publish Game
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Export Godot Web Build
        id: export
        uses: abarichello/godot-ci@v2
        with:
          name: web
          archive_output: true

      - name: Publish to Itch.io
        uses: manleydev/butler-publish-itchio-action@master
        env:
          BUTLER_CREDENTIALS: ${{ secrets.MONSTER_ON_ROAD }}
          CHANNEL: html
          ITCH_GAME: ${{ secrets.ITCH_GAME }}
          PACKAGE: ${{ steps.export.outputs.archive_directory }}/web.zip
